#!/bin/bash
# This script will take a directory name and will convert any .m4a file in this directory to .mp3
# =============================================================================================
# How to run:
#             1) IN the directory where you files are placed run the following command
                 $ convmp3 < complete_path_to_file_where_converted_files_are_to_be_stored >
count=0         #  initialize count variable
dest=$1         # destination folder where files to placed
IFS=$'\r\n'     # changing file separator field to match our requirements
for i in `ls`   
do
   name=`echo $i | cut -f 1 -d '.'`    # remove the extension of given file
   avconv -i $i  $dest/$name.mp3       # new name with new extension
   count=$($count+1)                   # track the count please
done

echo "$count jobs has beenn completed"


